#中心
receive:
  ip: 125.74.7.95
  port: 9010
  tables: event_statics as hmy_event_statics,pom_sentiment_recent as hmy_pom_sentiment_recent
  columns: city_code,execute_date,daily_total,daily_yesterday,daily_percent,daily_trend,history_good_total,history_good_yesterday,history_good_percent,history_bad_total,history_bad_yesterday,history_bad_percent,history_neutral_total,history_neutral_yesterday,history_neutral_percent,history_sick_total,history_sick_yesterday,history_sick_percent,history_sick_trend,statistics_date,create_time#id,title,medianame,sentiment,url,hex(url) as url_hex,outbreak,area_code,area_name,event_id,countdate,releasedate
  conditions: ( 1=1 )#( 1=1 )
  syncColumn: create_time,countdate
sync:
  time: 0 20 2 * * ?
  change: -180

task:
  size: 10

server:
  port: 9081
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ENC(pDBHRT5GVFK/24ad0wYrsA==)
      password: ENC(i5UYxSUwTqJzie3lYywoEyH58IYtGvLQ)
      url: ENC(EHrUWh1ByYbfZ2czXESuld3VLyZQ5PlVCYiw3DbNliNWLbbO1Go190VFbKnoOA7sSbebyitrfUMzZNHOQyYEMO7fvgJH7YORP8rLeZ5EpjCjbrF+Tw4ag+y7ppzbuajjIoE4no56r+4=)
